export default {
  START_DRAW_TIME: 'ドロータイムを開始',
  START_ENERGY_TIME: 'エナジータイムを開始',
  START_PUT_TIME: 'プットタイムを開始',
  START_SOMETHING_TIME: 'サムシングタイムを開始',
  START_BATTLE_TIME: 'バトルタイムを開始',
  START_END_TIME: 'エンドタイムを開始',
  FINISH_END_TIME: 'エンドタイムを終了',
  PUT_SOUL: 'ソウルゾーンにプット',
  CHANGE_BATTLE_POSITION: '表示形式変更',
  USE_SOUL_CANON: 'ソウルキャノン',
  SUMMON_MONSTER: '召喚',
  ATTACK: '攻撃',
  USE_SOUL_BARRIER: 'ソウルバリア',
};
